package com.shg.edu.sch;

import java.util.*;

import org.springframework.data.annotation.Id;

import com.utm.util.IModel;

@SuppressWarnings({"unused"})
@javax.annotation.Generated(value = "Autogenerated by ClassUtil Compiler (0.1)", date = "2018-12-20")
public class School implements IModel {
    private static final long serialVersionUID = 1L;

    /** 名称, 注意字段需要附带索引和optional或required标志 */
    public String name;
	/** 序号 */
    public Long sn = 0l;

    public School(){
    }

    public final String getName() { 
        return name; 
    }

    public final void setName(String name) { 
        this.name = name;
    }

    public final Long getSn() { 
        return sn; 
    }

    public final void setSn(Long sn) { 
        this.sn = sn;
    }


}
